env:
  - PPA=avsm/ocaml42+opam12

before_script:
  - sudo add-apt-repository -y ppa:$PPA
  - sudo apt-get update
  - sudo apt-get install ocaml-nox opam
  - ocaml -version
  - opam init -y
  - eval `opam config env`

script:
  - opam install -y ocamlfind oasis
  - make build test
  - make clean
  - opam remove -y ocamlfind
  - ln -s src/opam
  - opam pin add -y .
  - opam install oasis -y
  - make test OPAM_INSTALLATION=yes
